import { Fragment, useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { ChevronDown, ChevronRight, Download, X } from 'lucide-react';
import { query, health, type Row } from '../data/duckdb';
import { today } from '../data/analytics';
import { acquisitionFactsSQL, acquisitionPeriodLabel } from '../data/acquisition';
import { contributesToMetric, inclusionReasons, membershipUsed, metricFilter, referenceConverted, referenceHosted, referenceNew, referenceRetained, referenceSummary, type AcquisitionDrillRequest } from '../data/acquisition-reference';
import { fmt, formatField } from '../semantics/formats';
import { exportCSV } from './exports';
import { sourceRows } from '../data/raw';

const filters = [['contributors','Clicked metric contributors'],['all','All clients'],['eligible','New-client cohort'],['converted','Converted'],['retained','Retained'],['excluded','Outside new-client cohort'],['highValue','Above-average LTV'],['hosted','Hosted'],['converted30','Same-month converted'],['retained30','Same-month converted & retained'],['convertedMonth','First-month converted'],['retainedMonth','First-month retained']] as const;
const clientColumns = [['member','Community member'],['member_id','Member ID'],['email','Email'],['phone','Phone'],['entry_type','Client type'],['date','First visit'],['format','First visit entity'],['location','Studio'],['trainer','Instructor'],['membership','Membership used'],['conversion','Conversion status'],['retention','Retention status'],['first_purchase_date','First purchase date'],['product','First purchase item'],['first_purchase','First purchase value'],['purchase_journey','Purchase journey'],['post_trial_purchases','Post-trial purchases'],['visits_post','Post-trial visits'],['second_visit_days','Days to second visit'],['conversion_days','Conversion span'],['ref_membership_eligible','Eligible purchase list'],['mature','30-day observation complete'],['converted_in_30','Same-month converted'],['returned_in_30','Same-month converted & retained'],['converted_same_month','First-month converted'],['returned_same_month','First-month retained'],['ltv','LTV'],['avg_purchase_value','Average spend']] as const;
function display(key: string, value: unknown) {
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (key === 'date' || key.endsWith('_date')) return acquisitionPeriodLabel(value);
  if (['revenue','first_purchase','ltv','avg_purchase_value'].includes(key)) return fmt('avg_ltv',value);
  if (key.endsWith('_days')) return fmt('avg_conversion_span',value);
  return value == null ? '—' : String(value);
}
function matches(row: Row, sale: Row) {
  return (row.member_id != null && String(row.member_id) === String(sale.member_id)) || (row.email != null && String(row.email).toLowerCase() === String(sale.email ?? '').toLowerCase());
}
function Distribution({ title, rows, keyName }: {title:string;rows:Row[];keyName:string}) {
  const values = new Map<string,number>();
  rows.forEach(row => {const value = keyName==='membership' ? membershipUsed(row) : String(row[keyName] ?? 'Unspecified'); values.set(value,(values.get(value)??0)+1);});
  const sorted = [...values].sort((a,b)=>b[1]-a[1]).slice(0,6), max = sorted[0]?.[1] || 1;
  return <article className="acq-distribution"><h3>{title}</h3>{sorted.map(([value,count])=><div key={value}><div><span title={value}>{value}</span><strong>{count.toLocaleString('en-IN')}</strong></div><i style={{width:`${count/max*100}%`}} /></div>)}{!sorted.length&&<p>No source data in this slice.</p>}</article>;
}
function OriginalRow({ row }: {row:Row}) {
  const [original,setOriginal]=useState<Record<string,unknown>|null>(null), [error,setError]=useState('');
  useEffect(()=>{let active=true;sourceRows('new',[row]).then(data=>{if(active)setOriginal(data[0]);}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[row]);
  return error?<p role="alert">{error}</p>:original?<dl className="acq-original">{Object.entries(original).filter(([key])=>key.trim()).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{formatField(key,value)}</dd></div>)}</dl>:<p role="status">Loading original source fields…</p>;
}
function SalesTable({rows}:{rows:Row[]}) {
  return <div className="acq-table-scroll"><table className="acq-table"><thead><tr>{['Date','Community member','Member ID','Purchase','Category','Sale ID','Value','Payment status','Associate','Studio'].map(label=><th key={label} className={label==='Date'?'acq-sticky':undefined}>{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={String(row.source_row)}>{['date','member','member_id','product','category','sale_id','revenue','status','associate','location'].map(key=><td key={key} className={key==='date'?'acq-sticky':undefined}>{display(key,row[key])}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="acq-empty">No linked sale items in the available source coverage.</p>}</div>;
}
export function AcquisitionDrillDown({request,version,imports,onClose}:{request:AcquisitionDrillRequest;version:number;imports:boolean;onClose:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null);
  const [clients,setClients]=useState<Row[]>([]), [sales,setSales]=useState<Row[]>([]), [error,setError]=useState(''), [salesError,setSalesError]=useState(''), [salesLoading,setSalesLoading]=useState(true), [loading,setLoading]=useState(true);
  const [tab,setTab]=useState('clients'), [filter,setFilter]=useState(metricFilter(request.metric)), [search,setSearch]=useState(''), [page,setPage]=useState(0), [salesPage,setSalesPage]=useState(0), [expanded,setExpanded]=useState<string|null>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null; const oldOverflow=document.body.style.overflow;dialog.current?.showModal();document.body.style.overflow='hidden';return()=>{document.body.style.overflow=oldOverflow;previous?.focus();};},[]);
  useEffect(()=>{
    let active=true;setLoading(true);setError('');setSalesError('');setSales([]);setSalesLoading(true);
    const facts=acquisitionFactsSQL(request.scope,today());
    const slice=`SELECT * FROM (${facts}) facts ${request.predicate?`WHERE ${request.predicate}`:''}`;
    query(`${slice} ORDER BY date DESC,source_row`).then(rows=>{if(active){setClients(rows);setLoading(false);}}).catch(e=>{if(active){setError(String(e));setLoading(false);}});
    if(health.sales?.fetchedAt && health.sales.status!=='error') {
      query(`WITH clients AS (${slice}) SELECT s.* FROM sales s WHERE NOT COALESCE(s.voided,FALSE) AND (s.status='succeeded' OR s.status IS NULL) ${imports?'':'AND NOT s.imported'} AND (s.member_id IN (SELECT member_id FROM clients WHERE member_id IS NOT NULL) OR lower(s.email) IN (SELECT lower(email) FROM clients WHERE email IS NOT NULL)) ORDER BY s.date DESC,s.source_row`)
        .then(rows=>{if(active){setSales(rows);setSalesLoading(false);}}).catch(e=>{if(active){setSalesError(String(e));setSalesLoading(false);}});
    } else {setSalesError('Sales source unavailable. Refresh Member Acquisition to load linked transactions.');setSalesLoading(false);}
    return()=>{active=false;};
  },[request,version,imports]);
  const fullSummary=useMemo(()=>referenceSummary(clients,request.uniqueOutcomes),[clients,request.uniqueOutcomes]);
  const visible=useMemo(()=>clients.filter(row=>{
    const qualifies=(filter==='contributors'||filter===metricFilter(request.metric)&&filter!=='all')?contributesToMetric(row,request.metric,request.uniqueOutcomes):filter==='eligible'?referenceNew(row):filter==='converted'?referenceConverted(row):filter==='retained'?referenceRetained(row):filter==='excluded'?!referenceNew(row):filter==='highValue'?row.ltv!=null&&Number(row.ltv)>=(fullSummary.avg_ltv??Infinity):filter==='hosted'?referenceHosted(row):filter==='converted30'?Number(row.converted_in_30):filter==='retained30'?Number(row.returned_in_30):filter==='convertedMonth'?Number(row.converted_same_month):filter==='retainedMonth'?Number(row.returned_same_month):true;
    return qualifies && [row.member,row.member_id,row.email,row.entry_type,row.format,row.product,membershipUsed(row)].some(value=>String(value??'').toLowerCase().includes(search.toLowerCase()));
  }),[clients,filter,search,fullSummary.avg_ltv,request]);
  const summary=useMemo(()=>referenceSummary(visible,request.uniqueOutcomes),[visible,request.uniqueOutcomes]);
  const matchedSales=useMemo(()=>{const ids=new Set(visible.map(r=>r.member_id).filter(Boolean)), emails=new Set(visible.map(r=>r.email).filter(Boolean).map(e=>String(e).toLowerCase()));return sales.filter(s=>(s.member_id&&ids.has(s.member_id))||(s.email&&emails.has(String(s.email).toLowerCase())));},[visible,sales]);
  const saleCount=new Set(matchedSales.map(s=>s.sale_id).filter(Boolean)).size;
  const paymentRows=matchedSales.filter(r=>r.revenue!=null), matchedRevenue=paymentRows.length?paymentRows.reduce((sum,row)=>sum+Number(row.revenue),0):null;
  const currentPage=Math.min(page,Math.max(0,Math.ceil(visible.length/25)-1)), currentSalesPage=Math.min(salesPage,Math.max(0,Math.ceil(matchedSales.length/25)-1));
  const months=useMemo(()=>[...new Set(visible.map(r=>r.month).filter(Boolean))].sort().reverse().slice(0,14),[visible]);
  const cards=[['cohort_rows','Clients in slice','new_clients'],['newcomers','New-client cohort','new_clients'],['converted_members','Converted','new_clients'],['retained_members','Retained','new_clients'],['avg_ltv','Average LTV','avg_ltv'],['conversion_rate','Conversion rate','conversion_rate']] as const;
  return createPortal(<dialog ref={dialog} className="acq-drill-dialog" aria-labelledby="acq-drill-title" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}>
    <header className="acq-drill-head"><div><span className="acq-count">Member acquisition · source evidence</span><h2 id="acq-drill-title">{request.title}</h2><p>{request.metric?`Selected metric: ${request.metric.replaceAll('_',' ')} · `:''}{clients.length.toLocaleString('en-IN')} source cohort records</p></div><button aria-label="Close acquisition drill-down" onClick={onClose}><X size={19}/></button></header>
    {error?<p role="alert">{error}</p>:loading?<p className="acq-empty" role="status">Loading the selected cohort and linked purchases…</p>:<>
      <div className="acq-drill-summary">{cards.map(([key,label,formatter])=><div key={key}><span>{label}</span><strong>{fmt(formatter,fullSummary[key])}</strong></div>)}</div>
      <div className="acq-drill-tabs" role="group" aria-label="Drill-down views">{[['overview','Overview'],['clients','Client table'],['transactions','Transactions'],['methodology','Methodology']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>
      <div className="acq-drill-toolbar"><label>Client filter<select aria-label="Drill-down client filter" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);setSalesPage(0);}}>{filters.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><input aria-label="Search drill-down clients" placeholder="Search member, ID, package or experience…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);setSalesPage(0);}}/><span>{visible.length.toLocaleString('en-IN')} shown</span><button onClick={()=>exportCSV('acquisition-drill-clients',visible.map(row=>Object.fromEntries(clientColumns.map(([key,label])=>[label,key==='membership'?membershipUsed(row):display(key,row[key])]))))}><Download size={14}/>Export filtered clients</button></div>
      <p className="acq-drill-context">Member rows are limited to the clicked row and period. The selected metric filter shows its contributing records; choose All clients to inspect the denominator. Same-month outcomes count unique member IDs; repeated cohort records remain visible. {request.uniqueOutcomes ? 'Instructor outcomes count unique member IDs; multiple source records for the same member may be shown.' : ''}</p><div className="acq-drill-body">
        {tab==='overview'&&<>
          <div className="acq-analytics-grid">{[['Membership mix','membership'],['Top locations','location'],['Instructor touchpoints','trainer'],['First-visit experiences','format'],['Conversion status mix','conversion'],['Retention status mix','retention']].map(([title,keyName])=><Distribution key={title} title={title} rows={visible} keyName={keyName}/>)}</div>
          <div className="acq-analytics-grid"><article className="acq-distribution"><h3>Cohort outcomes</h3><p>Source statuses can overlap. Rates use new-client records as the denominator.</p>{[['Clients / trials',summary.cohort_rows],['New clients',summary.newcomers],['Converted',summary.converted_members],['Retained',summary.retained_members]].map(([label,value])=><div key={String(label)}><div><span>{label}</span><strong>{value}</strong></div><i style={{width:`${Math.min(100,Number(value)/(summary.cohort_rows||1)*100)}%`}}/></div>)}</article>
          <article className="acq-distribution"><h3>Linked purchase evidence</h3>{salesError?<p role="alert">{salesError}</p>:salesLoading?<p role="status">Loading linked purchase evidence…</p>:<><p>{matchedSales.length.toLocaleString('en-IN')} sale item lines · {saleCount.toLocaleString('en-IN')} known sale IDs</p><strong>{fmt('avg_ltv',matchedRevenue)} recorded collections</strong><p>Unique sale items are counted once, even when a member appears in several cohorts. Linked sales span available payment dates, separate from first-visit months.</p></>}</article>
          <article className="acq-distribution"><h3>Conversion & practice</h3><p>{fmt('avg_conversion_span',summary.conversion_span)} average positive conversion span</p><p>{fmt('avg_conversion_span',summary.visits_post).replace('d','')} average positive post-trial visits</p><p>{fmt('conversion_rate',summary.retention_rate)} retention rate · {fmt('avg_ltv',summary.avg_spend)} source average spend</p></article></div>
          <article className="acq-distribution"><h3>First-visit cohort trend</h3><div className="acq-table-scroll"><table className="acq-table"><thead><tr>{['Period','Clients / trials','New','Converted','Retained','Conversion rate','Retention rate','Average LTV'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{months.map(month=>{const stats=referenceSummary(visible.filter(row=>row.month===month),request.uniqueOutcomes);return <tr key={String(month)}><td>{acquisitionPeriodLabel(month)}</td>{['cohort_rows','newcomers','converted_members','retained_members','conversion_rate','retention_rate','avg_ltv'].map(key=><td key={key}>{fmt(key.includes('rate')?'conversion_rate':key==='avg_ltv'?'avg_ltv':'new_clients',stats[key as keyof typeof stats])}</td>)}</tr>;})}</tbody></table></div></article>
        </>}
        {tab==='clients'&&<><div className="acq-table-scroll"><table className="acq-table"><thead><tr>{clientColumns.map(([,label],i)=><th key={label} className={i===0?'acq-sticky':undefined}>{label}</th>)}</tr></thead><tbody>{visible.slice(currentPage*25,currentPage*25+25).map(row=>{const key=String(row.source_row),open=expanded===key,reasons=inclusionReasons(row);return <Fragment key={key}><tr>{clientColumns.map(([field],i)=>i===0?<th key={field} scope="row" className="acq-sticky"><button className="acq-expand" aria-expanded={open} onClick={()=>setExpanded(open?null:key)}>{open?<ChevronDown size={13}/>:<ChevronRight size={13}/>}<span>{row.member??'Unnamed member'}</span></button></th>:<td key={field}>{field==='membership'?membershipUsed(row):display(field,row[field])}</td>)}</tr>{open&&<tr className="acq-expanded-purchase"><td colSpan={clientColumns.length}><div className="acq-client-evidence"><h3>Inclusion & exclusion evidence</h3><p>{reasons.cohort}</p><p>{reasons.conversion}</p><p>{reasons.retention}</p><h3>Chronological purchase journey</h3>{salesError?<p role="alert">{salesError}</p>:salesLoading?<p role="status">Loading linked purchases…</p>:<SalesTable rows={sales.filter(s=>matches(row,s)).sort((a,b)=>String(a.date).localeCompare(String(b.date)))}/>}<details><summary>Original source fields</summary><OriginalRow row={row}/></details></div></td></tr>}</Fragment>;})}</tbody></table>{!visible.length&&<p className="acq-empty">No clients match these filters.</p>}</div><div className="acq-pagination"><span>Page {currentPage+1} of {Math.max(1,Math.ceil(visible.length/25))}</span><div><button disabled={!currentPage} onClick={()=>setPage(currentPage-1)}>Previous</button><button disabled={(currentPage+1)*25>=visible.length} onClick={()=>setPage(currentPage+1)}>Next</button></div></div></>}
        {tab==='transactions'&&<>{salesError?<p role="alert">{salesError}</p>:salesLoading?<p role="status">Loading linked purchase evidence…</p>:<><div className="acq-transaction-summary"><span>{matchedSales.length} sale item lines · {saleCount} known sales · {matchedSales.filter(s=>!s.sale_id).length} lines missing sale ID</span><strong>{fmt('avg_ltv',matchedRevenue)}</strong><button onClick={()=>exportCSV('acquisition-linked-sales',matchedSales)}>Export filtered sales</button></div><SalesTable rows={matchedSales.slice(currentSalesPage*25,currentSalesPage*25+25)}/><div className="acq-pagination"><span>Page {currentSalesPage+1} of {Math.max(1,Math.ceil(matchedSales.length/25))}</span><div><button disabled={!currentSalesPage} onClick={()=>setSalesPage(currentSalesPage-1)}>Previous</button><button disabled={(currentSalesPage+1)*25>=matchedSales.length} onClick={()=>setSalesPage(currentSalesPage+1)}>Next</button></div></div></>}</>}
        {tab==='methodology'&&<article className="acq-methodology"><h3>Reference analytics definitions</h3><dl>
          <dt>New-client cohort</dt><dd>Is New contains the word new. Repeat, staff/family and blank labels stay outside the denominator.</dd>
          <dt>Converted</dt><dd>Conversion Status is exactly Converted. The post-trial purchase list is shown for context but does not change the count.</dd>
          <dt>Retained</dt><dd>Retention Status is exactly Retained. In the current source this holds for every row with at least one post-trial visit.</dd>
          <dt>Rates</dt><dd>Converted / new clients and retained / new clients, using source cohort rows. Instructor tables use unique member IDs. A non-new status can still contribute to the reference numerator, so some rates may exceed 100%. A zero denominator stays unavailable.</dd>
          <dt>Calendar-month outcomes</dt><dd>Eligible conversion purchase on or after the first visit, in the same calendar month and year. Retained also requires the source Retained status; a second visit alone does not qualify. Counts use identified members and do not require a 30-day observation window.</dd>
          <dt>Lifetime value & spend</dt><dd>Source-reported LTV and average purchase values. Missing values stay unavailable. Positive conversion spans and post-trial visits use the reference's positive-value averaging.</dd>
          <dt>Transactions</dt><dd>Successful non-voided sale item lines matched by member ID or email. All available payment dates are included. Sale items are counted once; transaction totals use distinct known sale IDs. Linked collections are separate from cohort LTV and package-attributed LTV.</dd>
          <dt>Slice and filters</dt><dd>The header describes the full clicked slice. Client filters and search update Overview, Client table and Transactions together. Date, group and child selections come from the clicked cell. Source freshness: {health.new?.fetchedAt?new Date(health.new.fetchedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'unavailable'}.</dd>
        </dl><h3>Currently filtered cohort</h3><p>{summary.cohort_rows} records · {summary.newcomers} new-client records · {summary.converted_members} converted · {summary.retained_members} retained</p><p>Incomplete sales, missing member identities, missing timing, and missing source columns remain visible as coverage limits.</p></article>}
      </div>
    </>}
  </dialog>,document.body);
}
