import {useState} from 'react';
import {fmt} from '../semantics/formats';
import {acquisitionPeriodLabel} from '../data/acquisition';
export type Period={from:string;to:string;revenue:number|null;saleItems:number;knownSales:number;knownItems:number;averageItemValue:number|null;members:number;leads:number;scheduled:number;completed:number;scheduledRate:number|null;completedRate:number|null;due:number;matureDue:number;renewed:number;unrecorded:number;missingDates:number;lapsed:number;churnRate:number|null;grace:number};
export type Explanation={finding:string;basis:string;action:string};
export type Topic={id:string;category:string;title:string};
export type TopicRecord={status:string;note:string;date:string;basis?:string};
export function KraPeriodComparisons({periods,trajectories,explanations}:{periods:Record<string,Period>;trajectories:Record<string,string>;explanations:Record<string,Explanation>}) {
  const rows:[keyof Period,string,string,string][]=[
    ['revenue','Revenue','currency','revenue'],['saleItems','Paid item lines','count','revenue'],['averageItemValue','Average payment-item value','currency','revenue'],['members','Identified paying members','count','revenue'],
    ['leads','Lead cohort','count','trials'],['scheduled','First class scheduled','count','trials'],['completed','First class completed','count','trials'],['scheduledRate','Lead → scheduled rate','percent','trials'],['completedRate','Lead → completed rate','percent','trials'],
    ['matureDue','Mature membership expiries','count','churn'],['lapsed','Mature lapsed memberships','count','churn'],['churnRate','Mature-cohort lapse rate','percent','churn'],
  ];
  function display(value:unknown,type:string){return value==null?type==='percent'?'No eligible denominator':'Source reconciliation required':fmt(type==='currency'?'revenue':type==='percent'?'conversion_rate':'new_clients',value);}
  function movement(value:unknown,previous:unknown){if(value==null||previous==null)return 'Source reconciliation';if(Number(previous)===0)return Number(value)===0?'No movement (both 0)':'New baseline';return fmt('conversion_rate',Number(value)/Number(previous)-1);}
  return <section className="kra-panel"><header><h3>KRA period totals & comparative performance</h3><span className="small">Equal elapsed days for the preceding-period comparison</span></header>
    <div className="kra-comparison-ranges">{[['current','KRA to date'],['lastYear','Same period last year'],['precedingMatched','Preceding KRA period · matched days'],['precedingFull','Full preceding 6-month period']].map(([key,label])=><div key={key}><strong>{label}</strong><span>{acquisitionPeriodLabel(periods[key].from)} – {acquisitionPeriodLabel(periods[key].to)}</span><b>{fmt('revenue',periods[key].revenue)}</b></div>)}</div>
    <div className="table-scroll"><table><thead><tr>{['Metric','KRA total / rate','Same period LY','Preceding period (matched)','Change vs LY','Change vs preceding','Target trajectory','Interpretation'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(([key,label,type,area])=><tr key={key}><td>{label}</td><td>{display(periods.current[key],type)}</td><td>{display(periods.lastYear[key],type)}</td><td>{display(periods.precedingMatched[key],type)}</td><td>{movement(periods.current[key],periods.lastYear[key])}</td><td>{movement(periods.current[key],periods.precedingMatched[key])}</td><td><span className={'kra-trajectory '+(trajectories[area]==='On track'?'positive':'attention')}>{trajectories[area]}</span></td><td className="kra-wrap">{key==='revenue'||key==='averageItemValue'?explanations.revenue.finding:area==='trials'?explanations.trials.finding:area==='churn'?explanations.churn.finding:'Payment volume and paying-member counts give context to collections; they are not independent KRA targets.'}</td></tr>)}</tbody><tfoot><tr><td>Framework total</td><td>100% KRA weight</td><td colSpan={6}>Current actuals · comparative rates use their own denominators · no future revenue included</td></tr></tfoot></table></div>
    <div className="kra-explanation-grid">{Object.entries(explanations).map(([key,explanation])=><article key={key}><h4>{key==='stability'?'Revenue stability':key==='revenue'?'Revenue growth':key==='churn'?'Churn reduction':'Trials & referrals'}</h4><strong>{trajectories[key]}</strong><p>{explanation.finding}</p><p className="small">{explanation.basis}</p><p><b>Suggested next steps: </b>{explanation.action}</p></article>)}</div>
  </section>;
}
export function MarketingCurriculum({topics,records,onSaved}:{topics:Topic[];records:Record<string,TopicRecord>;onSaved:(id:string,record:TopicRecord)=>void}) {
  const [filter,setFilter]=useState('All'),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const completed=topics.filter(topic=>records[topic.id]?.status==='Completed').length;
  async function update(id:string,status:string){setBusy(id);setError('');try{const response=await fetch('/api/kra/training/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,note:records[id]?.note??''})});const result=await response.json();if(!response.ok)throw Error(result.error);onSaved(id,result);}catch(error){setError(error instanceof Error?error.message:String(error));}finally{setBusy('');}}
  return <section className="kra-panel"><header><h3>Performance marketing training · topic checklist</h3><strong>{completed} / {topics.length} completed · {topics.length?Math.round(completed/topics.length*100):0}%</strong></header>
    <p className="small">Mark your completed topics manually. Progress is saved with the date you report it; nothing is pre-marked.</p>
    <div className="acq-metric-tabs">{['All','Completed','In progress','Not started'].map(value=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{value}</button>)}</div>
    {error&&<p role="alert">{error}</p>}<div className="table-scroll"><table><thead><tr>{['Topic','Category','Progress','Reported date','Action'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{topics.filter(topic=>filter==='All'||(records[topic.id]?.status??'Not started')===filter).map(topic=><tr key={topic.id}><td className="kra-wrap">{topic.title}</td><td>{topic.category}</td><td>{records[topic.id]?.status??'Not started'}</td><td>{records[topic.id]?.date?acquisitionPeriodLabel(records[topic.id].date):'Not yet reported'}</td><td><select aria-label={'Progress for '+topic.title} disabled={busy===topic.id} value={records[topic.id]?.status??'Not started'} onChange={event=>void update(topic.id,event.target.value)}>{['Not started','In progress','Completed'].map(value=><option key={value}>{value}</option>)}</select></td></tr>)}</tbody><tfoot><tr><td>Total training topics</td><td>{topics.length}</td><td>{completed} completed</td><td colSpan={2}>Manually reported progress · upskilling weight 10%</td></tr></tfoot></table></div>
  </section>;
}
