export const currentSnapshotMetrics = new Set(["active_base", "active_memberships", "dormant_actives", "revenue_at_risk_30d"]);
export const metricNotes: Record<string, { definition: string; caveat?: string; numerator?: string; denominator?: string }> = {
  website_trials: { definition: "Website creation-date cohort records with Trial Status equal to Trial Completed. Outcomes are the latest recorded status, not trial events occurring during this period." },
  website_members: { definition: "Website creation-date cohort records with Conversion Status equal to Converted; current stage does not change this count." },
  website_retained: { definition: "Website creation-date cohort records with Retention Status equal to Retained." },
  website_win_rate: { definition: "Converted Website lead records divided by all Website lead records in the creation-date cohort." },
  website_trial_win_rate: { definition: "Website leads with both a completed trial and a conversion, divided by Website leads with a completed trial." },
  website_pipeline_value: { definition: "Open Website leads × cohort conversion rate × average positive paid first purchase of converted newcomers in the same scope.", caveat: "An estimate, not measured revenue. The New sheet supplies the first-purchase basis." },
  meta_leads: { definition: "Sum of the Meta sheet's leads column within the reporting date scope.", caveat: "Meta-reported conversions are not identified CRM people; do not add these to Website lead counts." },
  meta_instant_leads: { definition: "Sum of on_facebook_lead from Meta.", caveat: "May overlap the leads column; these counts are not added together." },
  meta_reach: { definition: "Sum of reach across the source rows.", caveat: "Audiences can repeat across dates, campaigns and platforms. This is not deduplicated reach." },
  meta_frequency: { definition: "Summed impressions divided by summed row reach.", caveat: "Not deduplicated campaign frequency; the source does not supply a unique-audience denominator for combined periods." },
  meta_cpl: { definition: "Summed Meta spend divided by summed Meta-reported leads. Unavailable when no leads are recorded." },
  meta_cpa: { definition: "Summed Meta spend divided by summed Meta-reported purchases. Unavailable when no purchases are recorded." },
  meta_roas: { definition: "Summed Meta purchase value divided by summed spend.", caveat: "Uses the sheet's Meta reporting attribution. It is not CRM cash revenue or a CRM return on ad spend." },
  crm_google_leads: { definition: "Lead records explicitly tagged Google in UTM Source or Source Name. Conflicting Google/Meta tags are kept separate.", caveat: "A channel tag does not establish paid acquisition. Website-only records cannot be assigned to Google." },
  crm_meta_leads: { definition: "Lead records explicitly tagged Meta, Facebook, Instagram, fb or ig in UTM Source or Source Name. Conflicting Google/Meta tags are kept separate.", caveat: "Includes platform-tagged records whose paid/organic status is unknown. Not directly matched to Meta-reported lead events." },
  complimentary_visits: {definition:"Sum of numeric values in the Sessions Complimentary column within the selected scope.",caveat:"Independent of NonPaid and check-in complimentary flags; missing source values stay unavailable."},
  session_complimentary_rate: {definition:"Sessions complimentary visit count divided by Sessions CheckedIn attendance."},
  lapsed_members: { definition: "Distinct members whose most recent paid membership lapsed (has a Churned Date), counted when that membership expires in the period. Zero-value memberships and restricted names (intro, 2 for 1, studio single class, private, credit, Copper + Cloves single class, test) are ignored when finding the most recent membership; a member whose latest membership is Frozen is not lapsed.", caveat: "A member who bought another paid membership after the lapse is not counted. Restricted names follow the KRA churn rules in server/kra-churn.mjs." },
  revenue: { definition: "Revenue attributed to studio sessions in the selected date range.", caveat: "Recognised earned revenue differs from cash collected on the Revenue & sales tab." },
  discount_value: { definition: "Sale-item unit discount multiplied by quantity, summed across payment lines.", caveat: "Sale-level discount totals repeat on multi-item sales and are not summed as item discounts." },
  discount_rate: { definition: "Item-level discounts divided by collected revenue plus those discounts.", caveat: "Uses unit discount × quantity, not the sale-level discount repeated on each row." },
  gross_revenue: { definition: "Payments collected on successful, non-voided sale lines, by payment date.", caveat: "Cash collections and session-attributed revenue have different timing and populations." },
  net_revenue: { definition: "Successful payment value less the VAT recorded on those same payment lines.", caveat: "Uses collected payment and payment VAT; the source catalogue price is not collected net revenue." },
  late_affected_sessions: { definition: "Distinct source session identities with at least one late-cancelled booking in this scope.", caveat: "Uses session ID, source unique IDs, then date, time, format and studio when an ID is unavailable." },
  late_recorded_value: { definition: "Source Sale Value attributed to late-cancelled booking rows, excluding imported bookings.", caveat: "Recorded booking value is not measured lost cash, a refund or a cancellation fee." },
  fill_rate: { definition: "Attendees divided by available seats across the same sessions.", numerator: "Attendees", denominator: "Available seats" },
  avg_class_size_incl: { definition: "Total attendees divided by sessions, including empty sessions.", numerator: "Attendees", denominator: "Sessions" },
  conversion_rate: { definition: "Trials whose Conversion Status is Converted, divided by every trial. A trial is any row whose Is New label contains the word new.", numerator: "Converted trials", denominator: "Trials", caveat: "Outcome is the source's latest status, not conversions occurring during this period." },
  retention_rate: { definition: "Trials whose Retention Status is Retained, divided by every trial.", numerator: "Retained trials", denominator: "Trials", caveat: "In the current source Retained holds for exactly the trials with a post-trial visit, so this matches the second-visit rate." },
  second_visit_rate: { definition: "Trials with at least one post-trial visit divided by every trial. Counted from Visits Post Trial, not from a status column.", numerator: "Returned trials", denominator: "Trials", caveat: "The source derives Retention Status from the same column, so this currently equals the retention rate." },
  checkin_revenue: { definition: "Attributed revenue from checked-in rows only.", caveat: "Unattended and late-cancelled rows are excluded, matching session attendance revenue." },
  revenue_per_checkin: { definition: "Attributed revenue on attended rows divided by attended check-ins.", numerator: "Attended revenue", denominator: "Check-ins" },
  teaching_hours: { definition: "Recorded duration counted once per attended session, converted to hours.", caveat: "Date-formatted minutes are decoded from the Sheets serial value; invalid or missing duration is excluded. Attendee rows never multiply teaching time." },
  revenue_per_hour: { definition: "Attended revenue with valid session duration divided by distinct-session teaching hours.", caveat: "Revenue and hours use the same duration-covered population." },
  payroll_revenue: { definition: "Monthly instructor-attributed revenue reported by Payroll.", caveat: "Payroll is monthly and source amounts are rounded; it may differ slightly from Sessions." },
  deferred_revenue: { definition: "Remaining membership money, counted once per membership in the selected sale cohort.", caveat: "A current balance from the source snapshot; not a historical balance at the selected period end." },
  lost_revenue: { definition: "Unoccupied seats valued at the current average revenue per attendee.", caveat: "A scenario estimate; it assumes every available seat earns the observed yield. It is not measured lost sales or a forecast." },
  draw_premium_pp: { definition: "Attendance fill rate minus the capacity-weighted fill rate of comparable location, format, weekday and time slots.", caveat: "The slot baseline includes all instructors even when an instructor filter is selected. The overall portfolio premium is expected to be zero." },
  converted_leads: { definition: "Lead records whose Stage Name is exactly Membership Sold, ignoring case and surrounding spaces." },
  trials_completed: { definition: "Lead records whose Stage Name is exactly Trial Completed; stage variants do not qualify." },
  lead_conversion_rate: { definition: "Lead records at the Membership Sold stage divided by all lead records in the selected creation-date cohort." },
  pipeline_value: { definition: "Open leads multiplied by the observed win rate and average paid first purchase of converted newcomers in the same global scope.", caveat: "An estimate, not contracted sales. Newcomer data loads with Enquiries so results do not depend on tab visit order." },
  active_base: { definition: "Distinct members whose latest lifecycle status is Active, across all first-visit dates.", caveat: "Current snapshot measure; period comparisons and historical trend are unavailable." },
  dormant_actives: { definition: "Running memberships (started, not yet expired, not Lapsed, Not Activated or Frozen) with more than 21 days since the last visit.", caveat: "Current snapshot measure. Date filters and historical comparisons are excluded." },
  revenue_at_risk_30d: { definition: "Purchase value of running memberships expiring from today through the next 30 days. Memberships already Renewed are excluded because their renewal is secured.", caveat: "Uses upcoming expiry dates relative to today; date filters and historical comparisons are excluded." },
  active_memberships: { definition: "Running memberships: access started and not yet expired, with status Active, New or Renewed. Frozen, Lapsed and Not Activated memberships are excluded.", caveat: "Current snapshot. The trend counts memberships running at each month end by access dates only, because historical status is not recorded." },
};
const formulas: Record<string, [string, string]> = {
  fill_rate: ["SUM(checked_in)", "SUM(capacity)"],
  avg_class_size_incl: ["SUM(checked_in)", "SUM(sessions)"],
  conversion_rate: ["COUNT(*) FILTER (WHERE is_new AND conversion='Converted')", "COUNT(*) FILTER (WHERE is_new)"],
  retention_rate: ["COUNT(*) FILTER (WHERE is_new AND retention='Retained')", "COUNT(*) FILTER (WHERE is_new)"],
  second_visit_rate: ["COUNT(*) FILTER (WHERE is_new AND visits_post>0)", "COUNT(*) FILTER (WHERE is_new)"],
  revenue_per_checkin: ["SUM(revenue) FILTER (WHERE attended)", "COUNT(*) FILTER (WHERE attended)"],
};
export function evidenceSQL(id: string) {
  const pair = formulas[id];
  return pair ? `, ${pair[0]} AS "${id}__numerator", ${pair[1]} AS "${id}__denominator"` : "";
}
